stages:
  - predelivery

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

#######
# Scans
#######
dependency-track-sbom:
  stage: predelivery
  image:
    name: composer:2.6
    entrypoint: [""]
  variables:
    BOM_FILE: "bom.xml"
  before_script:
    - git branch
    - apk add --no-cache libxml2-dev
    - docker-php-ext-install soap
    - composer install --no-interaction --no-progress
  script:
    - echo "Generating CycloneDX SBOM..."
    - composer CycloneDX:make-sbom --output-format xml --output-file $BOM_FILE
    - echo "Uploading BOM to Dependency-Track..."
    - |
      curl -X "POST" "${DT_HOST_URL}" \
      -H "Content-Type: multipart/form-data" \
      -H "X-Api-Key: ${DTRACK_API_KEY}" \
      -F "autoCreate=true" \
      -F "isLatest=true" \
      -F "projectName=${CI_PROJECT_NAME}" \
      -F "projectVersion=${CI_COMMIT_TITLE}" \
      -F "bom=@${BOM_FILE}"
      #-F "project=$PROJECT_UUID" \
      #for projetVersion, can be used : $CI_COMMIT_TITLE, $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME, $CI_MERGE_REQUEST_TITLE
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "predelivery"'
#  when: manual

sonarqube-scan:
  stage: predelivery
  image:
    name: sonarsource/sonar-scanner-cli:10
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  script:
    - |
      sonar-scanner \
      -Dsonar.host.url="${SONAR_HOST_URL}" \
      -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
      -Dsonar.projectVersion="${CI_COMMIT_TITLE}" \
      -Dsonar.token="${SONAR_TOKEN}"
      #for projetVersion, can be used : $CI_COMMIT_TITLE, $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME, $CI_MERGE_REQUEST_TITLE
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "predelivery"'
#  when: manual

secret_detection:
  stage: predelivery
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "predelivery"'
#  when: manual
