<?php
/** @var $block \Monext\Payline\Block\Adminhtml\Logs  */
$result = $block->getFileContent();
?>

<?php if (isset($result['content'])): ?>
    <div id="log_display" class="log_container">

            <?= /* @noEscape */ $result['content']; ?>
    </div>

<?php else : ?>
<p><?= /* @noEscape */ $result['error'] ?? ''; ?></p>
<?php endif; ?>

<button
    id="payline_download_logs"
    class="button action-configure"
    type="button"
    style="margin-top: 10px;"
    onclick="window.location = '<?php echo $block->getUrl('payline/logs/download'); ?>'; return false;">
    <span><?php echo __('Download Logs') ?></span>
</button>
